<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630134734 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dining_table (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(10) NOT NULL, seats INT NOT NULL, status VARCHAR(255) NOT NULL, establishment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_25538028565851 ON dining_table (establishment_id)');
        $this->addSql('CREATE TABLE dish (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, category VARCHAR(255) NOT NULL, price NUMERIC(6, 2) NOT NULL, allergens TEXT DEFAULT NULL, active BOOLEAN NOT NULL, establishment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_957D8CB88565851 ON dish (establishment_id)');
        $this->addSql('CREATE TABLE establishment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, city VARCHAR(120) NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DBEFB1EE989D9B62 ON establishment (slug)');
        $this->addSql('CREATE TABLE "order" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dining_table_id INT NOT NULL, reservation_id INT DEFAULT NULL, server_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F5299398695B08DC ON "order" (dining_table_id)');
        $this->addSql('CREATE INDEX IDX_F5299398B83297E7 ON "order" (reservation_id)');
        $this->addSql('CREATE INDEX IDX_F52993981844E6B7 ON "order" (server_id)');
        $this->addSql('CREATE TABLE order_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, seat_number INT DEFAULT NULL, status VARCHAR(255) NOT NULL, unit_price NUMERIC(6, 2) NOT NULL, order_id INT NOT NULL, dish_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52EA1F098D9F6D38 ON order_item (order_id)');
        $this->addSql('CREATE INDEX IDX_52EA1F09148EB0CB ON order_item (dish_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_name VARCHAR(120) NOT NULL, customer_email VARCHAR(180) NOT NULL, customer_phone VARCHAR(30) NOT NULL, date DATE NOT NULL, service VARCHAR(255) NOT NULL, party_size INT NOT NULL, allergies TEXT DEFAULT NULL, special_request TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, establishment_id INT NOT NULL, dining_table_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C849558565851 ON reservation (establishment_id)');
        $this->addSql('CREATE INDEX IDX_42C84955695B08DC ON reservation (dining_table_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, full_name VARCHAR(120) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, establishment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D6498565851 ON "user" (establishment_id)');
        $this->addSql('ALTER TABLE dining_table ADD CONSTRAINT FK_25538028565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dish ADD CONSTRAINT FK_957D8CB88565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398695B08DC FOREIGN KEY (dining_table_id) REFERENCES dining_table (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F5299398B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id)');
        $this->addSql('ALTER TABLE "order" ADD CONSTRAINT FK_F52993981844E6B7 FOREIGN KEY (server_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F098D9F6D38 FOREIGN KEY (order_id) REFERENCES "order" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_item ADD CONSTRAINT FK_52EA1F09148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849558565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955695B08DC FOREIGN KEY (dining_table_id) REFERENCES dining_table (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6498565851 FOREIGN KEY (establishment_id) REFERENCES establishment (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dining_table DROP CONSTRAINT FK_25538028565851');
        $this->addSql('ALTER TABLE dish DROP CONSTRAINT FK_957D8CB88565851');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398695B08DC');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F5299398B83297E7');
        $this->addSql('ALTER TABLE "order" DROP CONSTRAINT FK_F52993981844E6B7');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F098D9F6D38');
        $this->addSql('ALTER TABLE order_item DROP CONSTRAINT FK_52EA1F09148EB0CB');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849558565851');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955695B08DC');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6498565851');
        $this->addSql('DROP TABLE dining_table');
        $this->addSql('DROP TABLE dish');
        $this->addSql('DROP TABLE establishment');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE order_item');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE "user"');
    }
}
